### ISSUE TITLE
Implement ThirtyTwoByteHash for Hashes

### ISSUE THREAD

**Issue by D4nte** [rust-bitcoin/rust-secp256k1#106]
As per https://github.com/rust-bitcoin/rust-secp256k1/commit/e5a02bd9a0493f2bf0582e2082b5f79d0c8b6f45#commitcomment-32029345

`ThirtyTwoByteHash Trait` should be implemented for Hashes as currently `impl<T: ThirtyTwoByteHash> From<T> for Message` is unusable (or am I missing something?).

This would allow lib consumers to convert Hashes to Messages without an error path.

**Comment by apoelstra** [comment]
Unfortunately neither bitcoin_hashes nor rust-secp depend on each other, so it's hard to say which crate should have this implementation.

**Comment by elichai** [comment]
Either unwrap the `from_slice()` function because you can guarantee it works.
Or maybe adding `From<[u8; 32]>` without an error? (or `from_array`) 
Although I assume that the purpose of the `ThirtyTwoByteHash` trait is to make sure that people use the `Message` as a result of a hash and not directly on 32 byte data.

If so a theoretical solution might be `from_data` that receives a slice and hashes the data for you(I actually think this will be the safest API path, but will require some hash crate as a dependency which is not desirable)

**Comment by apoelstra** [comment]
If we're going to depend on a hash crate then we can just use `ThirtyTwoByteHash` directly for the 32-byte hashes.

**Comment by thomaseizinger** [comment]
This is the case [now](https://github.com/rust-bitcoin/rust-secp256k1/blob/12e3c66bec7d0fd6f46090e1e34a3fbd2fa1a681/src/lib.rs#L214-L226) can can be closed @apoelstra !
