### ISSUE TITLE
We should detect libgmp and use it if it's available

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-secp256k1#118]
So we stop getting stuff like https://twitter.com/bascule/status/1024313525554925568 which reflects poorly and unfairly on upstream.

**Comment by elichai** [comment]
Just curious,is it still constant time if we use libgmp?

**Comment by apoelstra** [comment]
Yes.

**Comment by apoelstra** [comment]
None of the constant-time code uses libgmp, only verification.

**Comment by elichai** [comment]
oh that makes sense.

**Comment by stevenroose** [comment]
I have no idea about libgmp and using it or whatever, but just looked at this because why not.

It seems that by default secp256k1 compilation will set `req_bignum` to `auto` which will use `gmp` if available. So if you say we are currently not using gmp, does our build somehow disable this? Or is the configure skipped for our build?

**Comment by stevenroose** [comment]
@jonasnick I guess you might understand more of this than I do :)

**Comment by apoelstra** [comment]
We do not use autotools at all.

**Comment by tcharding** [comment]
I think we can close this one because of https://github.com/rust-bitcoin/rust-secp256k1/pull/132#issuecomment-749485426 referencing upstreams dropping of gmp.

**Comment by elichai** [comment]
@tcharding You're right. libsecp no longer uses libgmp :)
