### ISSUE TITLE
Justification for unsafe impl of Send + Sync

### ISSUE THREAD

**Issue by thomaseizinger** [rust-bitcoin/rust-secp256k1#33]
I was looking into whether or not an instance of `Secp256k1` is thread-safe.

Could you explain why it is safe to implement `Send` and `Sync` for `Secp256k1` although the underlying context is mutable?

https://github.com/rust-bitcoin/rust-secp256k1/blob/b433e7bb1e03f482a99f58111e239d38f62e65f4/src/lib.rs#L400-L407

I guess adding a comment to the code would be good.

**Comment by apoelstra** [comment]
Sure, I'll add a comment. But the reason is that the underlying context is never mutated except by functions that take a mutable reference to it, and the context object does not contain any references to data that it doesn't own.

**Comment by TheBlueMatt** [comment]
Sadly the nomicon really doesn't at all define when Send/Sync are acceptable, but I wonder if it's actually ok. If you create a context in one thread and then pass it to another, only the pointer is held in the struct, so if you pass it via some relaxed operations you may actually not have flushed the context to memory. I assume this is actually fine, only because Send/Sync is essentially useless without assuming some kind of release/acquire.

**Comment by apoelstra** [comment]
Heh, at that level of paranoia even `Vec` or `Box` could not be `Send`.

**Comment by TheBlueMatt** [comment]
Fair, i suppose. I just hate how undefined the stuff is.

**Comment by thomaseizinger** [comment]
Thanks for the fast response!

So I guess the underlying C-library is also thread-safe? Rust cannot check that obviously.

**Comment by apoelstra** [comment]
@thomaseizinger Yep, the underlying library is threadsafe.

@TheBlueMatt Yeah :(
