### ISSUE TITLE
More arithmetic for x-only public keys

### ISSUE THREAD

**Issue by thomaseizinger** [rust-bitcoin/rust-secp256k1#405]
Is there a plan to add more arithmetic functions for x-only public keys?

In particular, I would be after:

- Summing two x-only public keys (i.e. the equivalent of `PublicKey::combine`)
- Multiplying an x-only public key with itself (i.e. the equivalent of `PublicKey::mul_assign`)

**Comment by apoelstra** [comment]
There is no plan for these things -- `PublicKey::combine` is an API that we regret adding, but were unable to remove because of its use in the Lightning Network.

`mul_assign`, which does a multiplicative tweak rather than an additive one, was originally added because we thought it would be more efficient in some contexts than `add_assign` (whose x-only equivalent is `tweak_add`). But AFAIK it actually isn't any more efficient, and I'm not aware of any usecases. Though if you have one, I think we woudn't mind adding the API.

In any case -- both of these questions should be directed upstream.

**Comment by thomaseizinger** [comment]
Okay, closing then.
