### ISSUE TITLE
Change 'add_assign' to take a byte slice rather than another 'SecretKey'

### ISSUE THREAD

**Issue by omershlo** [rust-bitcoin/rust-secp256k1#47]
Hi, 

I encountered this limitation a few times for the use case of threshold and multi signatures. 
In practice tweaks are more likely to be hashes (or zero) than things that are conceptually "secret keys". 
Other elliptic curve libraries seems to allow this tweak and doing field arithmetic using zero element.

**Comment by apoelstra** [comment]
Sure, I'll add this because upstream allows tweaking by 0 and it's kinda ergonomic that we prevent this (you wind up needing extra branches for "no tweak").

But this library does not support threshold or multisignatures in any way. It is not an EC primitive library, it supports specific cryptosystems in ways that (hopefully) make it difficult to do insecure things.

**Comment by omershlo** [comment]
Thanks.
You are right about the usage of the library. We wrote an abstraction that allows to plug this lib for various cryptosystems more easily (https://github.com/KZen-networks/cryptography-utils/blob/rewrite_ec_abstract/src/elliptic/curves/secp256_k1.rs). That said, for every new construction built using this abstraction (such as threshold/multi sigs) further analysis is required.
