### ISSUE TITLE
Introduce git brief message policy

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-secp256k1#547]
I'm sorting through PRs to do the CHANGELOG for `secp256k1-sys` release and its not immediately obvious which PRs are to secp and which are to secp-sys. Could we introduce a policy in this repo to prefix the git commit brief message with the crate? So all PRs are one of these forms:
1. `secp256k1: Make epic improvement`
2. `secp256k1-sys: Make epic improvement`
3. `Make epic improvement` 

(3) is solely for changes that hit both crates.

We could even use `secp: ` and `secp-sys:` to save writing 256k1 all the time but I'm ok with either.

**Comment by apoelstra** [comment]
Sounds great! ACK.

I think that any changes really should be for one crate or the other (maybe with some minor API fixups in the other).

**Comment by tcharding** [comment]
> (maybe with some minor API fixups in the other)

This would, in my mind, require no prefix. Any PR that touches both needs to be considered for release notes of both, right? However patches limited to one do not even need to be considered when releasing the other.

Do you prefer long form or short form (`secp` vs `secp26k1:`), I prefer the short form.

**Comment by apoelstra** [comment]
>Any PR that touches both needs to be considered for release notes of both, right?

No, I think any API changes in secp-sys would be shielded from API users of secp.

> Do you prefer long form or short form (secp vs secp26k1:), I prefer the short form.

Either is good by me. Let's do short form.

**Comment by tcharding** [comment]
Sweet as, on both points.

**Comment by Kixunil** [comment]
I have my doubts about this. I found those prefixes annoying (in a different repo) as they were shortening already very strict 50 chars limit. And in case of differentiating crates that should be trivial by looking at which files are changed.

**Comment by Kixunil** [comment]
> We also don't have a commit message line length limit

At least vim auto-wraps and I've seen similar feature in some other editor. So maybe the implicit limit is already there.

**Comment by apoelstra** [comment]
I've noticed the auto-wrapping, but I usually just undo it when I hit it.

**Comment by tcharding** [comment]
> We also don't have a commit message line length limit here ... though maybe we should.

woa woa woa, hold the phone - we definitely uphold archaic, probably-for-a-good-reason-but-I've-never-figured-it-out, process rules around here, some of use even force feed new devs with these rules :)

But in all seriousness I do try to stick to this rule (I thought it was 54 chars not 50), I think it comes from the fact sending patches by email uses the brief message with `Subject: [PATCH] ` prefixed for the email subject header. And since we all love github now and don't send patches by email this rule is probably out of date, if that is the actual reason. But when github rugs bitcoin we may have to go back to email and mailing lists (which would be totally better IMO).

**Comment by tcharding** [comment]
>  I found those prefixes annoying

The kernel manages to use nested prefixes but yes it does reduce the number of chars available.

I'm okay to not introduce this if there is not 100% agreement. I definitely don't want to introduce annoying policy.

**Comment by apoelstra** [comment]
FWIW, when github rugs bitcoin I think we'll move to a competing centralized service rather than email :) maintaining a mailing list is a huge thankless job even when the list isn't also a critical component of the development workflow. And email makes it quite difficult/manual to keep track of long-term issues or pull requests.

Also FWIW, rust-secp gets away with fewer rules/process than rust-bitcoin, because we have far fewer developers and correspondingly fewer patches.

Finally, for my part, I'm fine with using prefixes but I don't feel strongly about it.

**Comment by Kixunil** [comment]
> I thought it was 54 chars not 50

I don't remember exactly either.

> if that is the actual reason

I believe the actual reason is the width of terminal being 80 characters and the decreased limit is reserved for formatting. But today's terminals are wider so I don't mind.

I still think that keeping the title as short as you can without significantly reducing the quality of the message is good. It should be easy to quickly scan through log and have an idea of what each commit does.
