### ISSUE TITLE
scalar_inverse and scalar_inverse_var

### ISSUE THREAD

**Issue by tsxiaofang** [rust-bitcoin/rust-secp256k1#583]
I need to use the functions rustsecp256k1_v0_8_0_scalar_inverse and rustsecp256k1_v0_8_0_scalar_inverse_var, Can this crate be exported.

**Comment by Kixunil** [comment]
IIUC `scalar_inverse` should be the same as `SecretKey::negate`, you just have to handle zero/infinity yourself.

```rust
#[derive(Copy, Clone)]
enum ScalarWithInfinity {
    Finite(Scalar),
    Infinity,
}

impl ScalarWithInfinity {
    fn inverse(self) -> Self {
        match self {
            ScalarWithInfinity::Finite(scalar) => SecretKey::try_from(scalar).map(SecretKey::negate).map(ScalarWithInfinity::Finite).unwrap_or(ScalarWithInfinity::Infinity),
            ScalarWithInfinity::Infinity => ScalarWithInfinity::Finite(Scalar::ZERO),
        }
    }
}
```

**Comment by apoelstra** [comment]
@Kixunil no, `scalar_inverse` does a multiplicative inverse while `SecretKey::negate` does an additive inverse.

But @tsxiaofang no, there is no way we can export those functions without dramatic changes upstream, because we would need to expose the internal `secp256k1_scalar` type, which doesn't even have the same in-memory representation across architectures and therefore has no stable ABI.

**Comment by Kixunil** [comment]
Hmm, I think they should be named accordingly.

**Comment by tsxiaofang** [comment]
OK. I've got it.
