### ISSUE TITLE
Cross compile for no_std environment build is failing at linking

### ISSUE THREAD

**Issue by isaac-asdf** [rust-bitcoin/rust-secp256k1#598]
I posted this in the hal crate for the microcontroller I'm working with [ESP32](https://github.com/esp-rs/esp-hal/discussions/481), but will cross post here in case it's something I'm just doing wrong with the initial set up. Am I supposed to build the C library manually, or use the crate `secp256k1-sys` to build the the library for use? I'm getting errors for the functions I'm calling that look like `: undefined reference to 'rustsecp256k1_v0_8_1_schnorrsig_sign'`

[Source code for project](https://github.com/isaac-asdf/esp32-nostr-client)

**Comment by apoelstra** [comment]
It's difficult to see what's happening since even `cargo tree` fails with `error: invalid toolchain name: 'esp'`. When I try moving/deleting `rust-toolchain.toml` I get ` process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -C link-arg=-Tlinkall.x -C link-arg=-nostartfiles -C link-arg=-Tesp32_rom_functions.x -L libsecp256k1/libsecp256k1.a -l secp256k1 --target xtensa-esp32-none-elf --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 1)`.

But the short answer is that yes, you should be compiling libsecp via `secp256k1-sys`. If you don't want to do this, you can add `RUSTFLAGS=--cfg=rust_secp_no_symbol_renaming` which will forgo compiling the included version of libsecp (and avoid doing the `rustsecp256k1_v0_8_1` prefixing of all the symbols); in that case you are responsible for compiling and linking a compatible version of libsecp into your project.

But having said this, your existing setup should Just Work, using `secp256k1-sys` (which is a dep of `secp256k1`), whose `build.rs` should build libsecp256k1 for you.

I checked my local copy of `secp256k1-sys` 0.8.1 in my cargo cache and it does appear to define and export that symbol..

**Comment by Kixunil** [comment]
@apoelstra IIRC you need to use a forked compiler for ESP (for now, until they upstream it).

**Comment by isaac-asdf** [comment]
@Kixunil is correct, ESP uses needs a forked compiler. Running `cargo tree` gave me:
```
├── secp256k1 v0.27.0
│   ├── rand v0.8.5
│   │   └── rand_core v0.6.4
│   ├── secp256k1-sys v0.8.1
│   │   [build-dependencies]
│   │   └── cc v1.0.79
│   └── serde v1.0.160 (*)
```

I'll try the step @apoelstra mentioned of compiling with `RUSTFLAGS=--cfg=rust_secp_no_symbol_renaming` and let y'all know if that worked

**Comment by apoelstra** [comment]
My guess is that if you compile with that flag, you'll get link errors of the form `undefined reference to secp256k1_schnorrsig_sign` (note no weird rust version prefixing) and the solution will be to link your own copy of libsecp in.

My guess about the original issue is that the ESP compiler is somehow incompatible with the link symbol shenanigans we do in this library ... though I have no idea who is at fault.

**Comment by Kixunil** [comment]
I'd guess this should be job for `cc`.

**Comment by isaac-asdf** [comment]
Yeah, the `RUSTFLAGS=--cfg=rust_secp_no_symbol_renaming` just gave me different errors. @Kixunil do you have any recommendations or resources I could look into for how troubleshooting this on the `cc` side? I'm also wondering if it would just be easier to try to cut out this crate and try to right the FFI bindings for the few functions I'm actually using (basically just Schnorr signing)

**Comment by apoelstra** [comment]
@isaac-asdf if you want to do that, you could try depending on `secp256k1-sys` directly

**Comment by Kixunil** [comment]
@isaac-asdf maybe you could first run their tests on ESP and see if anything fails, if it does report it to them, if it doesn't then it may be actually our problem.

**Comment by isaac-asdf** [comment]
The code I have compiles and runs as long as the signature portion is commented out. I'm testing if I can get it to compile and run with just including a more basic C function to see if it's just an xtensa linking issue with `cc`. If that doesn't run then I think I can just close this out as it would be a linking issue

**Comment by isaac-asdf** [comment]
The issue appears to be coming from the combo of `cc` and the Rust fork that the xtensa chip is using. I ran the code from [this repo](https://github.com/isaac-asdf/esp32-hal-cc-error) and got the same error message of `undefined reference to my_c_function`. Thanks for the help @Kixunil and @apoelstra!

**Comment by stonexang** [comment]
@isaac-asdf 
![image](https://github.com/user-attachments/assets/8f3d0f08-78b7-4c30-923c-c922860edbed)
hi，Did you resolve your issue in the end?
I'm encountering compatibility issues with secp256k1 while linking a Rust static library for ESP32. and I found the following message: 'c928380082b86401-secp256k1.o: file format not recognized'.

**Comment by isaac-asdf** [comment]
Yeah, I was able to get it functional. If you check out
github.com/isaac-asdf/esp32-nostr-client you can see a project I used it
on. The nostr-nostd dependency is where I actually pull in secp256k1, and
the key to getting it compiling is explained in the Setup on the readme.
(Setting the CC and AR environment variables)

Let me know if you have any questions on that
