### ISSUE TITLE
Incorrect FFI binding for `secp256k1_ec_pubkey_combine`

### ISSUE THREAD

**Issue by icmccorm** [rust-bitcoin/rust-secp256k1#669]
At least one foreign function declared in Rust seems to be using integer types with a different width than the underlying function definition in C. For example, here’s the declaration of `secp256k1_ec_pubkey_combine` in [secp256k1-sys](https://github.com/rust-bitcoin/rust-secp256k1/tree/master/secp256k1-sys)

```
pub fn secp256k1_ec_pubkey_combine(cx: *const Context,
                                   out: *mut PublicKey,
                                   ins: *const *const PublicKey,
                                   n: c_int)
                                   -> c_int;
```
The parameter `n` is declared to be a 32-bit C integer, but the corresponding C function is expecting a `size_t`, which could be larger depending on the platform:
```
int rustsecp256k1_v0_9_1_ec_pubkey_combine(
	const rustsecp256k1_v0_9_1_context* ctx,
	rustsecp256k1_v0_9_1_pubkey *pubnonce,
	const rustsecp256k1_v0_9_1_pubkey * const *pubnonces,
	size_t n)
```

**Comment by apoelstra** [comment]
Thank you for reporting this! It looks like this bug has been present for a long time. We probably need to backport a fix to several past versions.

I am surprised that this bug hasn't triggered any issues in practice. I suspect that on low-endian systems that pass integers in registers, the code accidentally does the right thing despite the size mismatch.

**Comment by Kixunil** [comment]
:open_mouth: These kind of errors are precisely why I'd like to use bindgen. If not for codegen then at least for verification that the code is correct.

**Comment by apoelstra** [comment]
Yeah, it's probably time to try bindgen again.

**Comment by icmccorm** [comment]
Just curious—what have been the issues with using bindgen in the past?

**Comment by apoelstra** [comment]
It's been close to a decade since I tried to use it, but I recall a few oddities that made things difficult:

* Newtyped function pointers that we didn't want to expand
* No Rust equivalent to various C types without pulling in the `libc` crate (this is still the case; rustlib's `c_size_t` is unstable and `c_char` is not available with our MSRV, for example)
* A weird API surface that did not exactly match any set header files (this is no longer true since we split up our headers nicely and there is no longer anything libsecp exposes that we don't want to)
* `SECP256K1_API` markers that needed to be defined away somehow

I also think there was some missing bindgen functionality, but I don't remember what it was and I doubt it's missing now.

**Comment by apoelstra** [comment]
Ok, so immediately [looking at the bindgen docs](https://rust-lang.github.io/rust-bindgen/library-usage.html) we see that it will produce bindings for specific architectures, and the expectation is that you bring it in as a build dependency so that it will be run on the build architecture.

Doing this would increase our MSRV and change our dep tree from one entry (`cc`) to 36 entries. So that is immediately a no-go.

I will experiment with using it locally or in CI, which maybe will at least find egregious errors where the bindings aren't even right on x86_64.

**Comment by apoelstra** [comment]
When running it from the command-line, I see we would need to do a fair bit of post-processing on the output. The big thing is its use of `::std::os::raw::c_uchar` (which I didn't know about; and the docs for `std::os::raw` say "use `core::ffi`" though the latter is clearly unfinished). Aside from being ugly this is not nostd-compatible. We can search-and-replace those with `u8`s. Though some cases are not as simple; it uses `::std::os::raw::c_longlong` as its "max alignment" type while we use `[u8; 16]` for the same purpose, for example.

Interestingly for `size_t` it just uses usize.

It also puts every function into a separate extern block, which I can live with, and adds ugly `#[doc]` annotations which can be deleted or converted using the `prettyplease` tool which is designed to prettify autogenerated code. It adds some useful unit tests for the size and alignment of all structures, which I like.

It turns `#define` constants into `pub const`s which have type `u32` which is not compatible with the functions these are supposed to be used in. Some of these constants we also don't want to export (the context creation flags e.g.). So this would require some filtering.

All in all this looks like too much work and I'd rather just fix the hand-written bindings.

**Comment by Kixunil** [comment]
> the expectation is that you bring it in as a build dependency so that it will be run on the build architecture.

the reason being:

> Often times C and C++ headers will have platform- and architecture-specific #ifdefs that affect the shape of the Rust FFI bindings we need to create to interface Rust code with the outside world.

Is that actually the case in secp256k1? If it doesn't do that, we can use xtask instead, which solves the dependency issues etc.

Can those other things be configured?

**Comment by apoelstra** [comment]
>Is that actually the case in secp256k1?

Nope. The implementation-defined contents of the opaque blob types may be architecture-dependent but their size and alignment are always the same (in terms of C primitive types anyway).

Then I did not see a way to configure it to use `u8` in place of `c_uchar`, or to change the `doc` annotations (and the docs explicitly suggest using an external tool for this).

**Comment by Kixunil** [comment]
So it seems the only hard blocker is `u8` vs `c_uchar` thing. I wonder how hard would it be to fix it.

**Comment by apoelstra** [comment]
We could probably just use `sed`.
