### ISSUE TITLE
Make the signing API use `Into<Message>`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-secp256k1#700]
See https://github.com/rust-bitcoin/rust-bitcoin/issues/2821#issuecomment-2143050338

**Comment by apoelstra** [comment]
Moved from rust-bitcoin to rust-secp. The rust-secp signing methods, which are all agnostic to what they are signing, should take an `Into<Message>`. 

I took a quick look at the rust-bitcoin signing methods (`Psbt::sign` was the only one that jumped out at me) and they sign specific things and should presumably take specific types.

**Comment by liamaharon** [comment]
Are we talking about signing apis that currently take `&Message` such as https://github.com/rust-bitcoin/rust-secp256k1/blob/36be55f0b30e3ed8af84f5c8328b540c090f0896/src/ecdsa/recovery.rs#L155-L160 ?

If so, changing to `Into<Message>` will begin requiring ownership of the message where previously a ref was acceptable. Is this intentional? An alternative would be `AsRef<Message>` which supports both refs and consuming the value.

**Comment by liamaharon** [comment]
A consequence of this is that the signing methods will require ownership of msg, whereas prior message could be passed as a ref. Is that OK?

**Comment by apoelstra** [comment]
Good catch. Yes, I think this is fine. Messages are 32-byte objects which is small enough that we want to pass them by value anyway.

We should maybe encourage implementors in the docs to make sure that their `Into<Message>` types are also `Copy`.
